# Local U-Boot serial config for booting StarryOS on OrangePi 5 Plus.
serial = "/dev/ttyS7"
baud_rate = "1500000"
dtb_file = "os/StarryOS/configs/board/orangepi-5-plus.dtb"

kernel_load_addr = "0x02000000"
fit_load_addr = "0x0a000000"

success_regex = []
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
]
